Repository boostcampwm-2021/WEB01-NPE, pull requests merged in 2021-11, with the labels that each got.

#12 Feature/#2 백엔드 기초 구조 잡기
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/App.ts
  backend/src/entities/PostAnswer.ts
  backend/src/entities/PostQuestion.ts
  backend/src/entities/PostQuestionHasTag.ts
  backend/src/entities/Tag.ts
  backend/src/entities/User.ts
  backend/src/graphql/index.ts
  backend/src/graphql/queries/UserQuery.ts
  backend/src/graphql/services/PostService.ts
  backend/src/graphql/services/UserService.ts
  backend/src/graphql/types/PostAnswerType.ts
  backend/src/graphql/types/PostQuestionType.ts
  backend/src/graphql/types/UserType.ts
  backend/test/.gitkeep
  backend/tsconfig.json
  frontend/package-lock.json
Labels: 프론트엔드, 기초작업

#13 Feature/#5#6 버튼, 스위치 아톰컴포넌트
  frontend/.storybook/main.js
  frontend/components/atoms/Button/button.stories.tsx
  frontend/components/atoms/Button/index.tsx
  frontend/components/atoms/Button/logout.png
  frontend/components/atoms/Button/styled.ts
  frontend/components/atoms/Button/user.png
  frontend/components/atoms/Switch/Switch.stories.tsx
  frontend/components/atoms/Switch/index.tsx
  frontend/components/atoms/Switch/styled.ts
  frontend/package-lock.json
Labels: 프론트엔드, Atom

#11 Feature/#4 텍스트 아토믹 컴포넌트
  frontend/components/atoms/ContentText/ContentText.stories.tsx
  frontend/components/atoms/ContentText/index.tsx
  frontend/components/atoms/ContentText/styled.ts
  frontend/components/atoms/HeaderText/HeaderText.stories.tsx
  frontend/components/atoms/HeaderText/index.tsx
  frontend/components/atoms/HeaderText/styled.ts
  frontend/components/atoms/SubTitleText/SubTitleText.stories.tsx
  frontend/components/atoms/SubTitleText/index.tsx
  frontend/components/atoms/SubTitleText/styled.ts
  frontend/components/atoms/TitleText/TitleText.stories.tsx
  frontend/components/atoms/TitleText/index.tsx
  frontend/components/atoms/TitleText/styled.ts
  frontend/pages/_app.tsx
  frontend/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-bold.woff
  frontend/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-bold.woff2
  frontend/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-regular.woff
  frontend/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-regular.woff2
  frontend/styles/fonts/fonts.ts
Labels: 프론트엔드, Atom

#10 Feature/#3 원형 이미지 아토믹 컴포넌트
  frontend/components/atoms/ProfileImage/ProfileImage.stories.tsx
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/next.config.js
Labels: 프론트엔드, Atom

#17 Feature/#7#8 검색바 그래프 아토믹 컴포넌트만들기
  frontend/components/atoms/Chart/Chart.stories.tsx
  frontend/components/atoms/Chart/index.tsx
  frontend/components/atoms/Chart/styled.ts
  frontend/components/atoms/SearchBar/SearchBar.stories.tsx
  frontend/components/atoms/SearchBar/index.tsx
  frontend/components/atoms/SearchBar/styled.ts
Labels: 프론트엔드, Atom

#33 Feature/#18 백엔드 쿼리 마무리
  backend/src/graphql/index.ts
  backend/src/graphql/queries/QuestionQuery.ts
  backend/src/graphql/queries/QuestionsQuery.ts
  backend/src/graphql/services/PostService.ts
  backend/src/graphql/types/TagType.ts
Labels: 백엔드, 기초작업

#22 Feature/#20 헤더 프로필 컴포넌트 구현
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/components/atoms/SubTitleText/SubTitleText.stories.tsx
  frontend/components/atoms/SubTitleText/index.tsx
  frontend/components/atoms/SubTitleText/styled.ts
  frontend/components/atoms/Text/Text.stories.tsx
  frontend/components/atoms/Text/index.tsx
  frontend/components/atoms/Text/styled.ts
  frontend/components/molecules/ProfileHeader/ProfileHeader.stories.tsx
  frontend/components/molecules/ProfileHeader/index.tsx
  frontend/components/molecules/ProfileHeader/styled.ts
Labels: 프론트엔드, Molecule

#32 Feature/#27 Molcule-프로필 드랍다운 UI 구현
  frontend/components/molecules/profile-dropdown/button.stories.tsx
  frontend/components/molecules/profile-dropdown/index.tsx
  frontend/components/molecules/profile-dropdown/logout.png
  frontend/components/molecules/profile-dropdown/styled.ts
  frontend/components/molecules/profile-dropdown/user.png
Labels: 프론트엔드, Molecule

#29 Refactor/#21 atom search bar 분리
  frontend/components/atoms/SearchInput/SearchBar.stories.tsx
  frontend/components/atoms/SearchInput/index.tsx
  frontend/components/atoms/SearchInput/styled.ts
  frontend/package-lock.json
Labels: 프론트엔드, Atom

#30 Feature/#24 atom 사이드바 태그버튼
  frontend/components/atoms/SideTag/index.tsx
  frontend/components/atoms/SideTag/sideTag.stories.tsx
  frontend/components/atoms/SideTag/styled.ts
Labels: 프론트엔드, Atom

#31 Feature/#25 atom 인디케이터 초록회색
  frontend/components/atoms/Indicator/Indicator.stories.tsx
  frontend/components/atoms/Indicator/index.tsx
  frontend/components/atoms/Indicator/styled.ts
Labels: 프론트엔드, Atom

#35 refactor: [FE] 스토리북 이름 리팩토링
  frontend/components/atoms/ContentText/ContentText.stories.tsx
  frontend/components/atoms/HeaderText/HeaderText.stories.tsx
  frontend/components/atoms/ProfileImage/ProfileImage.stories.tsx
  frontend/components/atoms/Text/Text.stories.tsx
  frontend/components/atoms/TitleText/TitleText.stories.tsx
Labels: 프론트엔드, Atom

#37 :truck: rename ProfileDropdown 스토리
  frontend/components/molecules/profile-dropdown/profileDropdown.stories.tsx
Labels: 버그, 프론트엔드

#39 :fire: Remove: SearchBar Atomic
  frontend/components/atoms/SearchBar/SearchBar.stories.tsx
  frontend/components/atoms/SearchBar/index.tsx
  frontend/components/atoms/SearchBar/styled.ts
  frontend/components/molecules/profile-dropdown/button.stories.tsx
Labels: 프론트엔드

#41 Refactor/#40 이미지 커스텀 로더 리팩토링
  frontend/components/atoms/Image/Image.stories.tsx
  frontend/components/atoms/Image/index.tsx
  frontend/components/atoms/ProfileImage/ProfileImage.stories.tsx
  frontend/components/atoms/ProfileImage/index.tsx
  frontend/components/molecules/ProfileHeader/index.tsx
  frontend/components/molecules/ProfileSummary/index.tsx
Labels: 프론트엔드, Atom, Molecule

#55 Fix/#51 멘토링회의 피드백 반영(Button, Switch, Indicator, SideTag)
  frontend/src/components/atoms/Button/index.tsx
  frontend/src/components/atoms/Button/styled.ts
  frontend/src/components/atoms/Indicator/index.tsx
  frontend/src/components/atoms/SideTag/index.tsx
  frontend/src/components/atoms/SideTag/sideTag.stories.tsx
  frontend/src/components/atoms/SideTag/styled.ts
  frontend/src/components/atoms/Switch/index.tsx
Labels: 프론트엔드

#56 Feature/#53 molecule 사이드바 태그검색창
  frontend/src/components/molecules/TagSearch/TagSearch.stories.tsx
  frontend/src/components/molecules/TagSearch/index.tsx
  frontend/src/components/molecules/TagSearch/styled.ts
Labels: 프론트엔드, Molecule

#50 feat: [FE] 프로필 버튼을 링크로 수정
  frontend/src/components/molecules/ProfileHeader/index.tsx
  frontend/src/components/molecules/ProfileHeader/styled.ts
  frontend/src/components/molecules/ProfileSummary/index.tsx
  frontend/src/components/molecules/ProfileSummary/styled.ts
Labels: 프론트엔드, Molecule

#48 Feature/#47 폰트 수정
  frontend/.storybook/preview-body.html
  frontend/.storybook/preview-head.html
  frontend/src/components/atoms/ContentText/styled.ts
  frontend/src/components/atoms/HeaderText/styled.ts
  frontend/src/components/atoms/Text/styled.ts
  frontend/src/components/atoms/TitleText/styled.ts
  frontend/src/pages/_app.tsx
  frontend/src/pages/index.tsx
  frontend/src/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-bold.woff
  frontend/src/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-bold.woff2
  frontend/src/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-regular.woff
  frontend/src/styles/fonts/NotoSansKR/noto-sans-kr-v21-latin_korean-regular.woff2
  frontend/src/styles/fonts/fonts.ts
  frontend/src/styles/globals.css
Labels: 프론트엔드

#61 Refactor/#60-export-import-as-index
  frontend/src/components/atoms/index.ts
  frontend/src/components/molecules/index.ts
Labels: 프론트엔드, 리팩토링

#62 Feature/#59-Template-단일검색결과리스트UI
  frontend/src/components/templates/SearchResults/SearchResults.stories.tsx
  frontend/src/components/templates/SearchResults/index.tsx
  frontend/src/components/templates/SearchResults/styled.ts
Labels: 프론트엔드, Template

#58 Feature/#52-Organism-단일검색결과UI
  frontend/src/components/organisms/SearchResult/SearchResult.stories.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/components/organisms/SearchResult/styled.ts
Labels: 프론트엔드, Organism

#70 Feature/#63 organism 사이드바
  frontend/src/components/atoms/SideTag/index.tsx
  frontend/src/components/atoms/SideTag/styled.ts
  frontend/src/components/atoms/TitleText/index.tsx
  frontend/src/components/molecules/TagSearch/index.tsx
  frontend/src/components/molecules/TagSearch/styled.ts
  frontend/src/components/organisms/SideBar/SideBar.stories.tsx
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/components/organisms/SideBar/styled.ts
Labels: 프론트엔드, Organism

#67 Feature/#42 헤더 구현
  frontend/.storybook/preview.js
  frontend/src/components/atoms/Logo/Logo.stories.tsx
  frontend/src/components/atoms/Logo/index.tsx
  frontend/src/components/atoms/Logo/logo.png
  frontend/src/components/atoms/Logo/styled.ts
  frontend/src/components/atoms/LogoFull/Logo.stories.tsx
  frontend/src/components/atoms/LogoFull/index.tsx
  frontend/src/components/atoms/LogoFull/logo.png
  frontend/src/components/atoms/LogoFull/styled.ts
  frontend/src/components/atoms/index.ts
  frontend/src/components/molecules/ProfileHeader/index.tsx
  frontend/src/components/molecules/ProfileHeader/styled.ts
  frontend/src/components/organisms/Header/Header.stories.tsx
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/Header/question.png
  frontend/src/components/organisms/Header/styled.ts
  frontend/src/components/organisms/Header/user.png
Labels: 프론트엔드, Atom, Molecule, Organism

#69 Feature/#68-Atomic-IconWithNumber
  frontend/src/components/atoms/IconWithNumber/IconWithNumber.stories.tsx
  frontend/src/components/atoms/IconWithNumber/comments.png
  frontend/src/components/atoms/IconWithNumber/index.tsx
  frontend/src/components/atoms/IconWithNumber/styled.ts
  frontend/src/components/atoms/IconWithNumber/views.png
Labels: 프론트엔드, Atom

#66 Feature/#65-Atomic-태그버튼 UI 완성
  frontend/src/components/atoms/Tag/Tag.stories.tsx
  frontend/src/components/atoms/Tag/index.tsx
  frontend/src/components/atoms/Tag/styled.ts
Labels: 프론트엔드, Atom

#74 Refactor/#73 organism 단일검색결과UI
  frontend/src/components/atoms/index.ts
  frontend/src/components/organisms/SearchResult/SearchResult.stories.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/components/organisms/SearchResult/styled.ts
Labels: 프론트엔드, Organism, 리팩토링

#75 Refactor/#72-Template-검색결과리스트-UI
  frontend/src/components/templates/SearchResults/index.tsx
Labels: 프론트엔드, Template, 리팩토링

#76 Feature/Query Tag 구현
  backend/src/graphql/services/PostService.ts
Labels: 백엔드

#78 Feature/#64 Tag 관련 쿼리 및 Docs 수정
  backend/src/graphql/index.ts
  backend/src/graphql/inputTypes/PostQuestionInput.ts
  backend/src/graphql/mutations/QuestionMutation.ts
  backend/src/graphql/queries/QuestionQuery.ts
  backend/src/graphql/queries/QuestionsQuery.ts
  backend/src/graphql/queries/TagQuery.ts
  backend/src/graphql/queries/TagsQuery.ts
  backend/src/graphql/queries/UserQuery.ts
  backend/src/graphql/services/PostService.ts
  backend/src/graphql/services/TagService.ts
  backend/src/graphql/types/PostAnswerType.ts
  backend/src/graphql/types/PostQuestionType.ts
  backend/src/graphql/types/TagType.ts
  backend/src/graphql/types/UserType.ts
Labels: 백엔드, 문서

#80 Feature/#71 page main페이지
  frontend/.storybook/main.js
  frontend/src/components/atoms/SearchInput/styled.ts
  frontend/src/components/molecules/TagSearch/index.tsx
  frontend/src/components/molecules/TagSearch/styled.ts
  frontend/src/components/organisms/Header/styled.ts
  frontend/src/components/organisms/SearchResult/styled.ts
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/components/organisms/SideBar/styled.ts
  frontend/src/components/templates/SearchResults/index.tsx
  frontend/src/components/templates/SearchResults/styled.ts
  frontend/src/pages/MainPage/MainPage.stories.tsx
  frontend/src/pages/MainPage/index.tsx
  frontend/src/pages/MainPage/styled.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드, Page

#91 Refactor/#83 atom refactoring
  frontend/src/components/atoms/Input/SearchBar.stories.tsx
  frontend/src/components/atoms/Input/index.tsx
  frontend/src/components/atoms/Input/styled.ts
  frontend/src/components/atoms/index.ts
  frontend/src/components/organisms/Header/index.tsx
Labels: 프론트엔드, Atom, 리팩토링

#92 :truck: rename: ProfileDropdown
  frontend/src/components/molecules/ProfileDropdown/ProfileDropdown.stories.tsx
  frontend/src/components/molecules/ProfileDropdown/index.tsx
  frontend/src/components/molecules/ProfileDropdown/logout.png
  frontend/src/components/molecules/ProfileDropdown/styled.ts
  frontend/src/components/molecules/ProfileDropdown/user.png
Labels: 프론트엔드, Molecule, 리팩토링

#88 Refactor/#84 Tag 검색 기능 쿼리 최적화
  backend/src/graphql/services/PostService.ts
Labels: 백엔드, 리팩토링

#94 Refactor/#85 Any 제거 및 type-graphql Framework 적용
  backend/package-lock.json
  backend/package.json
  backend/src/App.ts
  backend/src/entities/PostAnswer.ts
  backend/src/entities/PostQuestion.ts
  backend/src/entities/Tag.ts
  backend/src/entities/User.ts
  backend/src/graphql/index.ts
  backend/src/graphql/inputTypes/AddQuestionInput.ts
  backend/src/graphql/inputTypes/PostQuestionInput.ts
  backend/src/graphql/inputTypes/SearchQuestionInput.ts
  backend/src/graphql/mutations/QuestionMutation.ts
  backend/src/graphql/queries/QuestionQuery.ts
  backend/src/graphql/queries/QuestionsQuery.ts
  backend/src/graphql/queries/TagQuery.ts
  backend/src/graphql/queries/TagsQuery.ts
  backend/src/graphql/queries/UserQuery.ts
  backend/src/graphql/resolvers/QuestionResolver.ts
  backend/src/graphql/resolvers/TagResolver.ts
  backend/src/graphql/resolvers/UserResolver.ts
  backend/src/graphql/services/PostService.ts
  backend/src/graphql/services/TagService.ts
  backend/src/graphql/services/UserService.ts
  backend/src/graphql/types/PostAnswerType.ts
  backend/src/graphql/types/PostQuestionType.ts
  backend/src/graphql/types/TagType.ts
  backend/src/graphql/types/UserType.ts
  backend/tsconfig.json
Labels: 백엔드, 리팩토링

#87 Refactor/#82 atom 리팩토링 (WIP)
  frontend/src/components/atoms/Logo/Logo.stories.tsx
  frontend/src/components/atoms/Logo/fullLogo.png
  frontend/src/components/atoms/Logo/index.tsx
  frontend/src/components/atoms/Logo/styled.ts
  frontend/src/components/atoms/LogoFull/Logo.stories.tsx
  frontend/src/components/atoms/LogoFull/index.tsx
  frontend/src/components/atoms/LogoFull/styled.ts
  frontend/src/components/atoms/Text/Text.stories.tsx
  frontend/src/components/atoms/Text/index.tsx
  frontend/src/components/atoms/Text/styled.ts
  frontend/src/components/atoms/index.ts
  frontend/src/components/molecules/ProfileHeader/index.tsx
  frontend/src/components/molecules/ProfileSummary/index.tsx
  frontend/src/components/molecules/ProfileSummary/styled.ts
  frontend/src/components/organisms/Header/index.tsx
Labels: 프론트엔드, 리팩토링

#93 :sparkles: feat: molecules QuestionTitle 추가
  frontend/src/components/molecules/QuestionTitle/QuestionTitle.stories.tsx
  frontend/src/components/molecules/QuestionTitle/index.tsx
  frontend/src/components/molecules/QuestionTitle/styled.ts
Labels: 프론트엔드, Molecule

#101 Feature/#82 atoms, molcule일부 리팩토링
  frontend/src/components/atoms/Button/button.stories.tsx
  frontend/src/components/atoms/Button/index.tsx
  frontend/src/components/atoms/ContentText/ContentText.stories.tsx
  frontend/src/components/atoms/ContentText/index.tsx
  frontend/src/components/atoms/ContentText/styled.ts
  frontend/src/components/atoms/HeaderText/HeaderText.stories.tsx
  frontend/src/components/atoms/HeaderText/index.tsx
  frontend/src/components/atoms/HeaderText/styled.ts
  frontend/src/components/atoms/IconWithNumber/IconWithNumber.stories.tsx
  frontend/src/components/atoms/IconWithNumber/index.tsx
  frontend/src/components/atoms/Image/Image.stories.tsx
  frontend/src/components/atoms/Image/index.tsx
  frontend/src/components/atoms/Indicator/Indicator.stories.tsx
  frontend/src/components/atoms/Indicator/index.tsx
  frontend/src/components/atoms/Indicator/styled.ts
  frontend/src/components/atoms/Logo/Logo.stories.tsx
  frontend/src/components/atoms/Logo/index.tsx
  frontend/src/components/atoms/Logo/logo.png
  frontend/src/components/atoms/Logo/shortLogo.png
  frontend/src/components/atoms/SearchInput/index.tsx
  frontend/src/components/atoms/SideTag/index.tsx
  frontend/src/components/atoms/SideTag/sideTag.stories.tsx
  frontend/src/components/atoms/SideTag/styled.ts
  frontend/src/components/atoms/Switch/Switch.stories.tsx
  frontend/src/components/atoms/Switch/index.tsx
  frontend/src/components/atoms/Switch/styled.ts
  frontend/src/components/atoms/Tag/Tag.stories.tsx
  frontend/src/components/atoms/Tag/index.tsx
  frontend/src/components/atoms/Tag/styled.ts
  frontend/src/components/atoms/Text/Text.stories.tsx
  frontend/src/components/atoms/Text/index.tsx
  frontend/src/components/atoms/Text/styled.ts
  frontend/src/components/atoms/TitleText/TitleText.stories.tsx
  frontend/src/components/atoms/TitleText/index.tsx
  frontend/src/components/atoms/TitleText/styled.ts
  frontend/src/components/molecules/ProfileDropdown/index.tsx
  frontend/src/components/molecules/ProfileDropdown/styled.ts
  frontend/src/components/molecules/ProfileHeader/index.tsx
  frontend/src/components/molecules/ProfileHeader/styled.ts
  frontend/src/components/molecules/index.ts
Labels: 프론트엔드, Atom, 리팩토링

#102 Feature/#99 Mutation 마무리
  backend/src/entities/PostAnswer.ts
  backend/src/entities/PostQuestion.ts
  backend/src/entities/PostQuestionHasTag.ts
  backend/src/graphql/index.ts
  backend/src/graphql/inputTypes/AnswerInput.ts
  backend/src/graphql/inputTypes/QuestionInput.ts
  backend/src/graphql/resolvers/AnswerResolver.ts
  backend/src/graphql/resolvers/QuestionResolver.ts
  backend/src/graphql/services/PostService.ts
  backend/src/graphql/services/TagService.ts
Labels: 백엔드, API

#100 Feature/#98 로그인 UI 구현
  frontend/src/components/atoms/Button/index.tsx
  frontend/src/components/atoms/Image/index.tsx
  frontend/src/components/atoms/Logo/fullLogo.png
  frontend/src/components/atoms/Text/index.tsx
  frontend/src/components/atoms/Text/styled.ts
  frontend/src/components/molecules/LoginModal/LoginModal.stories.tsx
  frontend/src/components/molecules/LoginModal/github.png
  frontend/src/components/molecules/LoginModal/index.tsx
  frontend/src/components/molecules/LoginModal/styled.ts
  frontend/src/components/molecules/ProfileDropdown/ProfileDropdown.stories.tsx
  frontend/src/components/molecules/ProfileDropdown/index.tsx
  frontend/src/components/molecules/ProfileDropdown/styled.ts
  frontend/src/components/molecules/ProfileSummary/index.tsx
  frontend/src/components/molecules/QuestionTitle/QuestionTitle.stories.tsx
  frontend/src/components/molecules/QuestionTitle/index.tsx
  frontend/src/components/molecules/index.ts
  frontend/src/components/organisms/Header/Header.stories.tsx
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/Header/question.png
  frontend/src/components/organisms/Header/styled.ts
  frontend/src/components/organisms/Header/user.png
  frontend/src/components/organisms/SearchResult/index.tsx
Labels: 프론트엔드, Molecule, Organism

#104 Refactor/#90 molecule 및 organisms 리팩토링 구현
  frontend/src/components/atoms/Switch/index.tsx
  frontend/src/components/molecules/ProfileSummary/index.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/components/organisms/SideBar/index.tsx
Labels: 프론트엔드, Molecule, Organism, 리팩토링

#103 Setting/#79 graphql apollo
  frontend/package.json
  frontend/src/api/index.ts
Labels: 프론트엔드, 기초작업, API

#111 Feature/#99
  backend/src/graphql/resolvers/AnswerResolver.ts
  backend/src/graphql/services/PostService.ts
Labels: 백엔드

#109 Feature/#108 다이나믹 라우팅 - Question, Tag 검색결과 페이지 레이아웃
  frontend/src/pages/question/[id].tsx
  frontend/src/pages/tag/[name].tsx
Labels: 프론트엔드, 기초작업, Page

#113 Feature/#110 프론트엔드 데이터 타입 정의
  frontend/src/types/index.ts
Labels: 프론트엔드, 기초작업

#115 Feature/#114-setting-apollo-client
  frontend/src/lib/apolloClient.ts
  frontend/src/pages/_app.tsx
Labels: 프론트엔드, 기초작업, API

#122 :recycle: refactor: Organism-Question
  frontend/src/components/organisms/Question/Question.stories.tsx
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/components/organisms/Question/styled.ts
Labels: 프론트엔드, 리팩토링

#120 :recycle: refactor: Template-QuestionList
  frontend/src/components/templates/QuestionList/QuestionList.stories.tsx
  frontend/src/components/templates/QuestionList/index.tsx
  frontend/src/components/templates/QuestionList/styled.ts
  frontend/src/components/templates/SearchResults/SearchResults.stories.tsx
  frontend/src/components/templates/SearchResults/index.tsx
  frontend/src/components/templates/SearchResults/styled.ts
Labels: 프론트엔드, Template, 리팩토링

#121 :label: feat: Add Organism export
  frontend/src/components/organisms/index.ts
Labels: 프론트엔드, Organism

#125 Refactor/#119 atom
  frontend/src/components/atoms/Tag/Tag.stories.tsx
  frontend/src/components/atoms/Tag/index.tsx
  frontend/src/components/atoms/index.ts
  frontend/src/components/molecules/index.ts
Labels: 프론트엔드, Atom, 리팩토링

#124 :sparkles: feat: Add Molecules
  frontend/src/components/molecules/IconWithNumber/IconWithNumber.stories.tsx
  frontend/src/components/molecules/IconWithNumber/comments.png
  frontend/src/components/molecules/IconWithNumber/index.tsx
  frontend/src/components/molecules/IconWithNumber/styled.ts
  frontend/src/components/molecules/IconWithNumber/views.png
  frontend/src/components/molecules/TagList/TagList.stories.tsx
  frontend/src/components/molecules/TagList/index.tsx
  frontend/src/components/molecules/TagList/styled.ts
  frontend/src/components/molecules/ViewsAndComment/ViewsAndComment.stories.tsx
  frontend/src/components/molecules/ViewsAndComment/index.tsx
  frontend/src/components/molecules/ViewsAndComment/styled.ts
Labels: 프론트엔드, Molecule

#127 Feature/#126 로그인 로직 구현
  frontend/.gitignore
  frontend/package.json
  frontend/src/components/molecules/LoginModal/LoginModal.stories.tsx
  frontend/src/components/molecules/LoginModal/index.tsx
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/pages/_app.tsx
  frontend/src/pages/_document.tsx
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: 프론트엔드

#132 Feature/#129 프로필 페이지 구현
  frontend/src/components/atoms/Chart/index.tsx
  frontend/src/components/atoms/Image/Image.stories.tsx
  frontend/src/components/atoms/Image/index.tsx
  frontend/src/components/molecules/ProfileDropdown/ProfileDropdown.stories.tsx
  frontend/src/components/molecules/ProfileDropdown/index.tsx
  frontend/src/components/molecules/ProfileHeader/styled.ts
  frontend/src/components/organisms/Header/Header.stories.tsx
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/Header/styled.ts
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/pages/index.tsx
  frontend/src/pages/profile/index.tsx
Labels: 프론트엔드, Page

#139 Feature/#133 alias
  frontend/.babelrc
  frontend/next.config.js
  frontend/package.json
  frontend/tsconfig.json
Labels: 프론트엔드, 기초작업

#138 Docs/readme 업데이트
  README.md
Labels: 문서

#141 :sparkles: feat: Main-page
  frontend/src/pages/index.tsx
Labels: 프론트엔드, Page

#142 :label: chore: update alias
  frontend/.babelrc
  frontend/next.config.js
  frontend/tsconfig.json
Labels: 프론트엔드, 기초작업

#146 [Fix] Move pages/api/index.ts -> lib/api
  frontend/src/lib/index.ts
Labels: 버그, 프론트엔드, API

#149 Refactor/#148-MainPage
  frontend/src/components/molecules/QuestionTitle/index.tsx
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/pages/index.tsx
Labels: 프론트엔드, 리팩토링, Page

#151 Fix/#135 toast UI 빌드에러
  frontend/src/components/atoms/MDEditor/index.tsx
  frontend/src/components/atoms/MDViewer/index.tsx
Labels: 버그, 프론트엔드

#155 :sparkles: feat: Add API getOneQuestionByID
  frontend/src/lib/index.ts
Labels: 프론트엔드, API

#137 Feature/#136 검색바 로직 구현하기
  backend/package-lock.json
  backend/package.json
  backend/src/App.ts
  frontend/src/components/atoms/Input/index.tsx
  frontend/src/components/molecules/TagSearch/index.tsx
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/Header/styled.ts
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/lib/index.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드

#160 Feature/#147 프로필 페이지 및 신규 태그 Resolver
  backend/package.json
  backend/src/App.ts
  backend/src/entities/PostAnswer.ts
  backend/src/entities/Tag.ts
  backend/src/entities/User.ts
  backend/src/entities/UserHasTag.ts
  backend/src/graphql/services/PostService.ts
  backend/src/migrations/1636635559207-UserHasTagCountMigration.ts
  docker-compose.yaml
  frontend/package-lock.json
  frontend/src/lib/index.ts
  frontend/src/pages/profile/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드

#158 Feature/#156-Add-Mocule,Organisms
  frontend/src/components/molecules/Vote/index.tsx
  frontend/src/components/molecules/Vote/styled.ts
  frontend/src/components/organisms/AnswerDetail/index.tsx
  frontend/src/components/organisms/DetailBody/index.tsx
  frontend/src/components/organisms/DetailBody/styled.ts
  frontend/src/components/organisms/QuestionDetail/index.tsx
  frontend/src/components/organisms/QuestionDetail/styled.ts
Labels: 프론트엔드, Molecule, Organism

#157 Refactoring] ProfileSummary 리팩토링
  frontend/src/components/molecules/ProfileSummary/index.tsx
Labels: 프론트엔드, 리팩토링

#159 Update: Types
  frontend/src/types/index.ts
Labels: 프론트엔드, 기초작업

#162 Fix/#152 메인페이지 질문목록 UI수정
  frontend/src/components/atoms/MDEditor/MdEditor.stories.tsx
  frontend/src/components/atoms/MDEditor/index.tsx
  frontend/src/components/atoms/MDViewer/index.tsx
  frontend/src/components/molecules/ProfileSummary/styled.ts
  frontend/src/components/molecules/QuestionTitle/index.tsx
  frontend/src/components/molecules/QuestionTitle/styled.ts
  frontend/src/components/molecules/TagList/index.tsx
  frontend/src/components/molecules/TagList/styled.ts
  frontend/src/components/organisms/Question/Question.stories.tsx
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/components/organisms/Question/styled.ts
  frontend/src/components/templates/QuestionList/QuestionList.stories.tsx
Labels: 프론트엔드, 리팩토링

#154 Feature/#145 질문조회 페이지 구현
  frontend/src/pages/question/[id].tsx
Labels: 프론트엔드, Page

#167 :sparkles: Feature: 답변하기 기능 추가, APi작성 관련 컴포넌트 디자인
  frontend/src/components/organisms/AnswerRegister/index.tsx
  frontend/src/components/organisms/AnswerRegister/styled.ts
  frontend/src/components/organisms/DetailBody/index.tsx
  frontend/src/components/organisms/DetailBody/styled.ts
  frontend/src/components/organisms/index.ts
  frontend/src/lib/index.ts
  frontend/src/pages/question/[id].tsx
Labels: 프론트엔드, Page, API

#168 Fix/#164 Frontend 컴포넌트 코딩 컨벤션에 맞춰 리팩토링
  frontend/src/components/atoms/Button/index.tsx
  frontend/src/components/atoms/Chart/index.tsx
  frontend/src/components/atoms/Chart/styled.ts
  frontend/src/components/atoms/ContentText/index.tsx
  frontend/src/components/atoms/ContentText/styled.ts
  frontend/src/components/atoms/HeaderText/index.tsx
  frontend/src/components/atoms/HeaderText/styled.ts
  frontend/src/components/atoms/IconWithNumber/index.tsx
  frontend/src/components/atoms/IconWithNumber/styled.ts
  frontend/src/components/atoms/Indicator/index.tsx
  frontend/src/components/atoms/Input/index.tsx
  frontend/src/components/atoms/Logo/index.tsx
  frontend/src/components/atoms/MDEditor/index.tsx
  frontend/src/components/atoms/SearchInput/index.tsx
  frontend/src/components/atoms/SearchInput/styled.ts
  frontend/src/components/atoms/SideTag/index.tsx
  frontend/src/components/atoms/Switch/index.tsx
  frontend/src/components/atoms/Tag/index.tsx
  frontend/src/components/atoms/Tag/styled.ts
  frontend/src/components/atoms/Text/index.tsx
  frontend/src/components/atoms/TitleInput/index.tsx
  frontend/src/components/atoms/TitleText/index.tsx
  frontend/src/components/atoms/index.ts
  frontend/src/components/molecules/LoginModal/index.tsx
  frontend/src/components/molecules/ProfileDropdown/index.tsx
  frontend/src/components/molecules/ProfileHeader/index.tsx
  frontend/src/components/molecules/QuestionTitle/index.tsx
  frontend/src/components/molecules/QuestionTitle/styled.ts
  frontend/src/components/molecules/TagInput/index.tsx
  frontend/src/components/molecules/TagList/index.tsx
  frontend/src/components/molecules/TagSearch/index.tsx
  frontend/src/components/molecules/ViewsAndComment/index.tsx
  frontend/src/components/molecules/ViewsAndComment/styled.ts
  frontend/src/components/molecules/index.ts
  frontend/src/components/organisms/AnswerDetail/index.tsx
  frontend/src/components/organisms/DetailBody/index.tsx
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/components/organisms/QuestionDetail/index.tsx
  frontend/src/components/organisms/SearchResult/index.tsx
  frontend/src/components/organisms/SearchResult/styled.ts
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/components/templates/QuestionList/index.tsx
  frontend/src/components/templates/QuestionList/styled.ts
  frontend/src/components/templates/ResisterQuestion/index.tsx
Labels: 프론트엔드, 리팩토링

#170 Feature/#169
  frontend/next-auth.d.ts
  frontend/src/lib/token.ts
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: 프론트엔드

#172 Design/#171 질문상세페이지
  frontend/src/components/organisms/AnswerDetail/index.tsx
  frontend/src/components/organisms/AnswerDetail/styled.ts
  frontend/src/components/organisms/DetailBody/styled.ts
  frontend/src/components/organisms/QuestionDetail/index.tsx
  frontend/src/components/organisms/QuestionDetail/styled.ts
  frontend/src/pages/question/[id].tsx
Labels: 프론트엔드, Page, 디자인

#173 Feature/#165
  backend/jest.config.ts
  backend/package-lock.json
  backend/package.json
  backend/src/graphql/errors/NoSuchQuestionError.ts
  backend/src/graphql/services/PostService.ts
  backend/src/repositories/AnswerRepository.ts
  backend/src/repositories/QuestionRepository.ts
  backend/src/repositories/TagRepository.ts
  backend/src/repositories/UserRepository.ts
  backend/test/.gitkeep
  backend/test/service/PostService.test.ts
  backend/tsconfig.json
Labels: 백엔드, 리팩토링

#182 Fix/#174 MDEditor SSR 이슈 해결
  frontend/src/components/atoms/MDEditor/WrappedEditor.tsx
  frontend/src/components/atoms/MDEditor/index.tsx
  frontend/src/components/templates/ResisterQuestion/index.tsx
Labels: 버그, 프론트엔드, 리팩토링

#179 [FE/Feature] 프로필 페이지 Data fetch
  backend/src/entities/UserHasTag.ts
  backend/src/graphql/resolvers/TagResolver.ts
  backend/src/repositories/AnswerRepository.ts
  backend/src/repositories/QuestionRepository.ts
  backend/src/repositories/TagRepository.ts
  backend/src/repositories/UserHasTagRepository.ts
  backend/src/repositories/UserRepository.ts
  frontend/src/components/molecules/ProfileAnswer/index.tsx
  frontend/src/components/molecules/ProfileAnswer/styled.ts
  frontend/src/components/molecules/ProfileSummary/index.tsx
  frontend/src/components/organisms/ProfileAnswerSummary/index.tsx
  frontend/src/components/organisms/ProfileAnswerSummary/styled.ts
  frontend/src/components/organisms/ProfileQuestionSummary/index.tsx
  frontend/src/components/organisms/ProfileQuestionSummary/styled.ts
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/components/templates/QuestionList/index.tsx
  frontend/src/lib/index.ts
  frontend/src/pages/profile/[userId].tsx
Labels: 프론트엔드, 백엔드, API, 디자인

#178 모달창 중앙 정렬
  frontend/src/components/organisms/Header/styled.ts
Labels: 프론트엔드, 디자인

#183 Feature/#180 메인 무한스크롤링 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/templates/QuestionList/styled.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드, Page

#177 질문 작성 로직 구현
  frontend/src/components/atoms/TitleInput/Inputs.stories.tsx
  frontend/src/components/atoms/TitleInput/index.tsx
  frontend/src/components/templates/ResisterQuestion/index.tsx
  frontend/src/lib/index.ts
Labels: 프론트엔드

#186 로그인 access token 추가
  backend/package-lock.json
  backend/package.json
  backend/src/graphql/resolvers/AnswerResolver.ts
  backend/src/graphql/resolvers/QuestionResolver.ts
  backend/src/graphql/resolvers/UserResolver.ts
  backend/src/graphql/services/UserService.ts
  frontend/src/components/organisms/AnswerRegister/index.tsx
  frontend/src/components/templates/ResisterQuestion/index.tsx
  frontend/src/lib/index.ts
  frontend/src/lib/token.ts
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: 프론트엔드, 백엔드

#192 질문 작성 시 제목 5자 제한 validation
  frontend/src/components/templates/ResisterQuestion/index.tsx
Labels: 프론트엔드

#191 Fix/#190
  frontend/src/components/atoms/MDViewer/MDViewer.stories.tsx
  frontend/src/components/atoms/MDViewer/WrappedViewer.tsx
  frontend/src/components/atoms/MDViewer/index.tsx
  frontend/src/components/atoms/Switch/index.tsx
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/styles/globals.css
Labels: 프론트엔드, 리팩토링

#193 실시간 공유 필터링 구현
  frontend/src/components/organisms/SideBar/SideBar.stories.tsx
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/lib/index.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드

#199 :bug: fix: [FE] onColor 에러 수정
  frontend/src/components/atoms/Switch/index.tsx
  frontend/src/components/atoms/Switch/styled.ts
Labels: 버그, 프론트엔드

#201 질문 작성 페이지 태그 로직 구현
  frontend/src/components/molecules/TagInput/TagInput.stories.tsx
  frontend/src/components/molecules/TagInput/index.tsx
  frontend/src/components/molecules/TagSearch/TagSearch.stories.tsx
  frontend/src/components/molecules/TagSearch/index.tsx
  frontend/src/components/templates/ResisterQuestion/index.tsx
Labels: 프론트엔드

#202 yjs 기반 코드 에디터 공유 일부 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
  frontend/src/components/organisms/RealTimeEditor/index.tsx
  frontend/src/components/organisms/RealTimeEditor/styled.ts
  frontend/src/components/organisms/index.ts
  frontend/src/components/templates/RealTimeModal/index.tsx
Labels: 프론트엔드

#204 Feature/#197 LiveChat 컴포넌트 구현
  backend/src/socket/index.ts
  frontend/src/components/organisms/LiveChat/LiveChat.stories.tsx
  frontend/src/components/organisms/LiveChat/index.tsx
  frontend/src/components/organisms/LiveChat/styled.ts
  frontend/src/components/organisms/LiveChat/useChat.ts
  frontend/src/components/templates/RealTimeModal/index.tsx
Labels: 프론트엔드, 백엔드, Template

#205 yjs UI 개선 및 웹소켓서버 연결
  frontend/next-auth.d.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
  frontend/src/components/organisms/RealTimeEditor/editor.tsx
  frontend/src/components/organisms/RealTimeEditor/styled.ts
Labels: 프론트엔드

#210 [FE] Fix/#209 프로필 페이지 관련 버그 수정
  frontend/src/components/molecules/ProfileSummary/index.tsx
  frontend/src/lib/index.ts
  frontend/src/pages/profile/[userId].tsx
Labels: 버그, 프론트엔드

#216 :sparkles: feat: [FE] 답변 작성 로직 마무리
  frontend/src/components/organisms/AnswerRegister/index.tsx
Labels: 프론트엔드

#219 질문 코드별로 분리 구현
  frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
  frontend/src/components/organisms/RealTimeEditor/editor.tsx
Labels: 프론트엔드

#214 무한스크롤시 검색 필터링 적용
  frontend/src/components/molecules/TagInput/index.tsx
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/lib/index.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드

#220 질문, 질문조회 마크다운 뷰어 적용
  frontend/src/components/organisms/DetailBody/index.tsx
  frontend/src/components/organisms/DetailBody/styled.ts
  frontend/src/components/organisms/Question/index.tsx
Labels: 프론트엔드, 디자인

#222 Fix/#221 질문리스트 프로필 크기 고정 및 프로필 페이지 질문 리스트 UI수정
  frontend/src/components/molecules/ProfileSummary/styled.ts
  frontend/src/components/organisms/Question/styled.ts
  frontend/src/pages/profile/[userId].tsx
Labels: 프론트엔드, 리팩토링

#225 Feature/#223 에러 출력 모달창 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/molecules/Modal/index.tsx
  frontend/src/components/molecules/Modal/styled.ts
  frontend/src/components/molecules/index.ts
  frontend/src/components/organisms/AnswerRegister/index.tsx
  frontend/src/components/templates/ResisterQuestion/index.tsx
  frontend/src/pages/_document.tsx
  frontend/src/pages/question/[id].tsx
Labels: 프론트엔드, Molecule

#230 실시간 코드 공유 에디터 탬 추가/제거를 구현
  frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
  frontend/src/components/organisms/RealTimeEditor/editor.tsx
  frontend/src/components/organisms/RealTimeEditor/styled.ts
Labels: 프론트엔드

#241 질문글 삭제기능 추가
  frontend/src/components/organisms/QuestionDetail/index.tsx
  frontend/src/components/organisms/QuestionDetail/styled.ts
Labels: 프론트엔드, Page, API

#243 :sparkles: feat: WebRTC 시그널링 서버 소켓
  backend/src/socket/index.ts
Labels: 백엔드

#239 질문조회페이지 SEO적용
  frontend/src/pages/question/[id].tsx
Labels: 프론트엔드, SEO

#234 favicon 추가
  frontend/public/favicon.ico
  frontend/public/vercel.svg
Labels: 프론트엔드, 디자인

#237 코드 공유 에디터 작업 마무리
  backend/src/socket/index.ts
  frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
  frontend/src/components/organisms/RealTimeEditor/editor.tsx
  frontend/src/components/organisms/RealTimeEditor/index.tsx
  frontend/src/components/organisms/RealTimeEditor/styled.ts
  frontend/src/components/templates/RealTimeModal/index.tsx
Labels: 프론트엔드

#244 Refactor/#228 리팩터링 및 조회수, 답변개수 로직
  backend/package-lock.json
  backend/package.json
  backend/src/App.ts
  backend/src/dto/AnswerInput.ts
  backend/src/dto/QuestionInput.ts
  backend/src/dto/SearchQuestionInput.ts
  backend/src/entities/PostAnswer.ts
  backend/src/entities/PostQuestion.ts
  backend/src/entities/PostQuestionHasTag.ts
  backend/src/entities/Tag.ts
  backend/src/entities/User.ts
  backend/src/entities/UserHasTag.ts
  backend/src/errors/NoSuchQuestionError.ts
  backend/src/graphql/index.ts
  backend/src/graphql/services/PostService.ts
  backend/src/graphql/services/TagService.ts
  backend/src/graphql/services/UserService.ts
  backend/src/repositories/AnswerRepository.ts
  backend/src/repositories/PostQuestionHasTagRepostiory.ts
  backend/src/repositories/QuestionRepository.ts
  backend/src/repositories/TagRepository.ts
  backend/src/repositories/UserHasTagRepository.ts
  backend/src/repositories/UserRepository.ts
  backend/src/repositories/index.ts
  backend/src/resolvers/AnswerResolver.ts
  backend/src/resolvers/QuestionResolver.ts
  backend/src/resolvers/TagResolver.ts
  backend/src/resolvers/UserResolver.ts
  backend/src/resolvers/index.ts
  backend/src/services/PostService.ts
  backend/src/services/TagService.ts
  backend/src/services/UserService.ts
  backend/test/service/PostService.test.ts
  frontend/src/components/organisms/AnswerRegister/index.tsx
  frontend/src/components/organisms/ProfileQuestionSummary/index.tsx
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/lib/index.ts
  frontend/src/pages/question/[id].tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드, 리팩토링

#227 Refactor/#226 채팅창 실시간 인원 표시
  backend/src/socket/index.ts
  frontend/src/components/organisms/LiveChat/index.tsx
  frontend/src/components/organisms/LiveChat/styled.ts
Labels: 프론트엔드, 리팩토링

#250 Refactor/#246 메인페이지 사이드바 UI 수정
  frontend/src/components/atoms/SideTag/delete.svg
  frontend/src/components/atoms/SideTag/index.tsx
  frontend/src/components/atoms/SideTag/styled.ts
  frontend/src/components/molecules/TagSearch/index.tsx
  frontend/src/components/molecules/TagSearch/plus.svg
  frontend/src/components/molecules/TagSearch/plus2.svg
  frontend/src/components/molecules/TagSearch/styled.ts
  frontend/src/components/organisms/SideBar/filter.svg
  frontend/src/components/organisms/SideBar/hashtag.svg
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/components/organisms/SideBar/live.svg
  frontend/src/components/organisms/SideBar/styled.ts
  frontend/src/components/organisms/SideBar/tags.svg
Labels: 프론트엔드, 리팩토링

#252 feat: webRTC
  backend/src/socket/index.ts
  frontend/src/components/atoms/MDEditor/index.tsx
  frontend/src/components/atoms/Text/index.tsx
  frontend/src/components/organisms/AnswerRegister/index.tsx
  frontend/src/components/organisms/LiveAudioStream/Audio.tsx
  frontend/src/components/organisms/LiveAudioStream/MuteButton.tsx
  frontend/src/components/organisms/LiveAudioStream/StreamProfile.tsx
  frontend/src/components/organisms/LiveAudioStream/index.tsx
  frontend/src/components/organisms/LiveAudioStream/mic.png
  frontend/src/components/organisms/LiveAudioStream/styled.ts
  frontend/src/components/organisms/LiveAudioStream/useLocalStream.ts
  frontend/src/components/organisms/LiveAudioStream/webRTC.ts
  frontend/src/components/organisms/LiveChat/index.tsx
  frontend/src/components/organisms/Mike/index.tsx
  frontend/src/components/organisms/index.ts
  frontend/src/components/templates/RealTimeModal/index.tsx
  frontend/src/styles/globals.css
  frontend/src/types/index.ts
Labels: 프론트엔드

#257 Feature/#247 질문글 좋아요/싫어요 기능 구현
  backend/src/App.ts
  backend/src/entities/PostAnswer.ts
  backend/src/entities/QuestionThumb.ts
  backend/src/errors/AuthenticationError.ts
  backend/src/errors/AuthorizationError.ts
  backend/src/errors/NoSuchQuestionError.ts
  backend/src/errors/NoSuchUserError.ts
  backend/src/middlewares/AuthChecker.ts
  backend/src/middlewares/AuthMiddleware.ts
  backend/src/migrations/1637689386694-QuestionThumbTable.ts
  backend/src/repositories/QuestionThumbRepository.ts
  backend/src/repositories/index.ts
  backend/src/resolvers/AnswerResolver.ts
  backend/src/resolvers/QuestionResolver.ts
  backend/src/services/ThumbService.ts
  backend/src/types/index.d.ts
  backend/tsconfig.json
  frontend/src/components/molecules/Vote/index.tsx
  frontend/src/components/organisms/DetailBody/index.tsx
  frontend/src/components/organisms/QuestionDetail/index.tsx
  frontend/src/lib/apolloClient.ts
  frontend/src/lib/index.ts
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드, 리팩토링

#254 title 및 SEO 태그 설정
  frontend/src/components/templates/SEOHeader/index.tsx
  frontend/src/components/templates/index.ts
  frontend/src/pages/index.tsx
  frontend/src/pages/profile/[userId].tsx
  frontend/src/pages/question/[id].tsx
Labels: 프론트엔드, SEO

#256 프론트엔드 각종 버그 fix
  frontend/src/components/atoms/Image/Image.stories.tsx
  frontend/src/components/atoms/Image/index.tsx
  frontend/src/components/atoms/index.ts
  frontend/src/components/molecules/ProfileHeader/index.tsx
  frontend/src/components/molecules/ProfileSummary/index.tsx
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/Header/styled.ts
  frontend/src/components/organisms/LiveAudioStream/MuteButton.tsx
  frontend/src/components/organisms/LiveAudioStream/StreamProfile.tsx
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/components/organisms/SideBar/index.tsx
  frontend/src/lib/index.ts
  frontend/src/pages/profile/[userId].tsx
Labels: 버그, 프론트엔드

#267 [BE] Fix: 신규유저 회원가입 불가 버그 수정
  backend/src/services/UserService.ts
Labels: 버그, 백엔드

#271 simple-peer webRTC 구현
  backend/src/socket/index.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/organisms/LiveAudioStream/Audio.tsx
  frontend/src/components/organisms/LiveAudioStream/index.tsx
  frontend/src/components/organisms/LiveAudioStream/styled.ts
Labels: 프론트엔드, API

#268 Fix/#264 사이드바 상단에 붙는 버그 Fix
  frontend/src/components/organisms/SideBar/styled.ts
Labels: 버그, 프론트엔드

#261 실시간 모달 UI 개선
  frontend/src/components/organisms/RealTimeEditor/styled.ts
  frontend/src/components/templates/RealTimeModal/index.tsx
  frontend/src/components/templates/RealTimeModal/styled.ts
Labels: 프론트엔드, 디자인

#259 페이지 로고 및 코드 공유 탭 개선
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/RealTimeEditor/styled.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드, 디자인

#274 실시간 모달 닫을때 답변이 자동 입력되도록 구현
  backend/src/socket/index.ts
  frontend/src/components/organisms/AnswerRegister/index.tsx
  frontend/src/components/organisms/RealTimeEditor/WrappedEditor.tsx
  frontend/src/components/organisms/RealTimeEditor/editor.tsx
  frontend/src/components/organisms/RealTimeEditor/index.tsx
  frontend/src/components/templates/RealTimeModal/index.tsx
  frontend/src/pages/question/[id].tsx
Labels: 프론트엔드

#275 뱃지의 웹사이트 주소를 nullpointerexception.ml 로 업데이트
  README.md
Labels: 문서

#281 답변 채택 기능 구현
  backend/src/entities/PostQuestion.ts
  backend/src/errors/CommonError.ts
  backend/src/migrations/1637838136299-QuestionAdoptedColumn.ts
  backend/src/resolvers/AnswerResolver.ts
  backend/src/services/PostService.ts
  frontend/src/components/organisms/AnswerDetail/index.tsx
  frontend/src/components/organisms/DetailBody/index.tsx
  frontend/src/components/organisms/DetailBody/styled.ts
  frontend/src/lib/index.ts
  frontend/src/pages/question/[id].tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드

#282 Feature/#280 리더보드 구현
  backend/src/resolvers/QuestionResolver.ts
  backend/src/resolvers/UserResolver.ts
  backend/src/services/PostService.ts
  backend/src/services/UserService.ts
  frontend/src/components/organisms/LeaderBoard/index.tsx
  frontend/src/components/organisms/LeaderBoard/question.svg
  frontend/src/components/organisms/LeaderBoard/styled.ts
  frontend/src/components/organisms/LeaderBoard/thumbsup.svg
  frontend/src/components/organisms/LeaderBoard/trophy.svg
  frontend/src/components/organisms/index.ts
  frontend/src/lib/index.ts
  frontend/src/pages/index.tsx
Labels: 프론트엔드, Organism

#287 Fix/#286 태그 저장 안되는 버그 수정 및 리팩터링
  backend/.gitignore
  backend/package-lock.json
  backend/package.json
  backend/src/repositories/AnswerRepository.ts
  backend/src/repositories/AnswerThumbRepository.ts
  backend/src/repositories/QuestionRepository.ts
  backend/src/repositories/QuestionThumbRepository.ts
  backend/src/repositories/TagRepository.ts
  backend/src/repositories/UserHasTagRepository.ts
  backend/src/resolvers/TagResolver.ts
  backend/src/services/PostService.ts
  backend/src/services/TagService.ts
  backend/src/services/ThumbService.ts
  backend/src/types/request/index.d.ts
  backend/tsconfig.json
Labels: 버그, 백엔드, 리팩토링

#293 환경변수 분리
  frontend/src/components/templates/RealTimeModal/index.tsx
  frontend/src/lib/apolloClient.ts
Labels: 프론트엔드

#289 채택 상태가 짊문자에게만 보이는 버그 수정
  frontend/src/components/organisms/DetailBody/index.tsx
Labels: 버그, 프론트엔드

#291 질문상세페이지 질문글 요약 위치 조정
  frontend/src/components/organisms/DetailBody/styled.ts
Labels: 버그, 프론트엔드

#296 글작성 10자 제한
  frontend/src/components/organisms/AnswerRegister/index.tsx
  frontend/src/components/templates/ResisterQuestion/index.tsx
Labels: 프론트엔드

#302 질문 날짜 수정
  frontend/src/components/molecules/QuestionTitle/index.tsx
  frontend/src/components/organisms/Question/index.tsx
  frontend/src/components/organisms/QuestionDetail/index.tsx
  frontend/src/lib/index.ts
  frontend/src/types/index.ts
Labels: 버그, 프론트엔드

#303 메인 페이지 질문리스트 가로 너비 고정
  frontend/src/components/templates/QuestionList/styled.ts
Labels: 버그, 프론트엔드

#310 :recycle: refactor: type extends
  frontend/src/types/index.ts
Labels: 리팩토링
