Repository boostcampwm-2021/WEB01-NPE, pull requests merged in 2021-12, with the labels that each got.

#308 [FE] SideBar 중복 태그 추가 못하도록 수정
  frontend/src/components/organisms/SideBar/index.tsx
Labels: 버그, 프론트엔드

#316 채팅 스크롤 맨 아래로 가도록 수정
  frontend/src/components/organisms/LiveChat/index.tsx
  frontend/src/components/organisms/LiveChat/styled.ts
  frontend/src/components/organisms/LiveChat/useChat.ts
Labels: 프론트엔드, 리팩토링

#315 jwt key 를 .env 로 수정
  frontend/src/lib/apolloClient.ts
  frontend/src/pages/api/auth/[...nextauth].ts
Labels: 프론트엔드, 기초작업

#318 헤더 로고 크기 고정
  frontend/src/components/organisms/Header/index.tsx
  frontend/src/components/organisms/Header/styled.ts
Labels: 버그, 프론트엔드

#319 답변 작성 버그 수정
  frontend/src/components/organisms/AnswerRegister/index.tsx
Labels: 버그, 프론트엔드

#320 Fix/#286 백엔드 리팩토링 및 서비스 로직 테스트 코드 작성
  backend/.gitignore
  backend/jest.config.js
  backend/jest.config.ts
  backend/package-lock.json
  backend/package.json
  backend/src/App.ts
  backend/src/InjectionConfig.ts
  backend/src/dto/AnswerInput.ts
  backend/src/entities/PostAnswer.ts
  backend/src/entities/PostQuestion.ts
  backend/src/entities/Tag.ts
  backend/src/entities/User.ts
  backend/src/middlewares/Auth.ts
  backend/src/middlewares/AuthChecker.ts
  backend/src/repositories/Answer/AnswerRepository.ts
  backend/src/repositories/Answer/AnswerRepositoryImpl.ts
  backend/src/repositories/AnswerThumb/AnswerThumbRepository.ts
  backend/src/repositories/AnswerThumb/AnswerThumbRepositoryImpl.ts
  backend/src/repositories/PostQuestionHasTag/PostQuestionHasTagRepositoryImpl.ts
  backend/src/repositories/PostQuestionHasTag/PostQuestionHasTagRepostiory.ts
  backend/src/repositories/PostQuestionHasTagRepostiory.ts
  backend/src/repositories/Question/QuestionRepository.ts
  backend/src/repositories/Question/QuestionRepositoryImpl.ts
  backend/src/repositories/QuestionThumb/QuestionThumbRepository.ts
  backend/src/repositories/QuestionThumb/QuestionThumbRepositoryImpl.ts
  backend/src/repositories/Tag/TagRepository.ts
  backend/src/repositories/Tag/TagRepositoryImpl.ts
  backend/src/repositories/User/UserRepository.ts
  backend/src/repositories/User/UserRepositoryImpl.ts
  backend/src/repositories/UserHasTag/UserHasTagRepository.ts
  backend/src/repositories/UserHasTag/UserHasTagRepositoryImpl.ts
  backend/src/resolvers/AnswerResolver.ts
  backend/src/resolvers/QuestionResolver.ts
  backend/src/resolvers/TagResolver.ts
  backend/src/resolvers/UserResolver.ts
  backend/src/services/Answer/AnswerService.ts
  backend/src/services/Answer/AnswerServiceImpl.ts
  backend/src/services/PostService.ts
  backend/src/services/Question/QuestionService.ts
  backend/src/services/Question/QuestionServiceImpl.ts
  backend/src/services/Tag/TagService.ts
  backend/src/services/Tag/TagServiceImpl.ts
  backend/src/services/Thumb/ThumbService.ts
  backend/src/services/Thumb/ThumbServiceImpl.ts
  backend/src/services/User/UserService.ts
  backend/src/services/User/UserServiceImpl.ts
  backend/test/connection.ts
  backend/test/mockdata/AnswerMock.ts
  backend/test/mockdata/Mock.ts
  backend/test/mockdata/QuestionMock.ts
  backend/test/mockdata/TagMock.ts
  backend/test/mockdata/UserMock.ts
  backend/test/repository/UserRepository.test.ts
  backend/test/service/AnswerService.test.ts
  backend/test/service/PostService.test.ts
  backend/test/service/QuestionService.test.ts
  backend/test/service/UserService.test.ts
  backend/test/testInjectionConfig.ts
  backend/tsconfig.json
Labels: 백엔드, 테스트

#325 Feature/#324 모니터링 툴 도입과 백엔드 안정화
  .gitignore
  backend/Dockerfile
  backend/package-lock.json
  backend/package.json
  backend/src/App.ts
  backend/tsconfig.json
  docker-compose.yaml
Labels: 백엔드, 인프라 및 배포

#326 새로고침시 게시씩 2개 생성되는거 수정
  frontend/src/pages/index.tsx
Labels: 버그, 프론트엔드

#323 Fix/#322 커서 포인터로 변경
  frontend/src/components/molecules/Vote/styled.ts
  frontend/src/components/organisms/QuestionDetail/index.tsx
  frontend/src/components/organisms/QuestionDetail/styled.ts
  frontend/src/pages/profile/[userId].tsx
Labels: 프론트엔드, 디자인

#328 태그 질문 작성 후 프로필 안들어가는 버그 수정
  backend/src/services/Tag/TagService.ts
  backend/src/services/Tag/TagServiceImpl.ts
  frontend/src/lib/index.ts
  frontend/src/pages/profile/[userId].tsx
Labels: 버그, 프론트엔드, 백엔드

#332 Refactor/#330 Path alias 테스트 분리 및 백엔드 리팩터링
  backend/jest.config.js
  backend/package.json
  backend/src/App.ts
  backend/src/dto/AnswerInput.ts
  backend/src/dto/QuestionInput.ts
  backend/src/dto/UserDto.ts
  backend/src/entities/PostAnswer.ts
  backend/src/entities/PostQuestion.ts
  backend/src/entities/PostQuestionHasTag.ts
  backend/src/entities/Tag.ts
  backend/src/entities/User.ts
  backend/src/repositories/AnswerThumb/AnswerThumbRepository.ts
  backend/src/repositories/AnswerThumb/AnswerThumbRepositoryImpl.ts
  backend/src/repositories/PostQuestionHasTag/PostQuestionHasTagRepositoryImpl.ts
  backend/src/repositories/PostQuestionHasTag/PostQuestionHasTagRepostiory.ts
  backend/src/repositories/QuestionThumb/QuestionThumbRepository.ts
  backend/src/repositories/QuestionThumb/QuestionThumbRepositoryImpl.ts
  backend/src/repositories/Tag/TagRepository.ts
  backend/src/repositories/UserHasTag/UserHasTagRepository.ts
  backend/src/repositories/UserHasTag/UserHasTagRepositoryImpl.ts
  backend/src/resolvers/TagResolver.ts
  backend/src/resolvers/UserResolver.ts
  backend/src/services/Tag/TagService.ts
  backend/src/services/Tag/TagServiceImpl.ts
  backend/src/services/Thumb/ThumbServiceImpl.ts
  backend/src/services/User/UserService.ts
  backend/src/services/User/UserServiceImpl.ts
  backend/test/integration/connection.ts
  backend/test/integration/mockdata/AnswerMock.ts
  backend/test/integration/mockdata/Mock.ts
  backend/test/integration/mockdata/QuestionMock.ts
  backend/test/integration/mockdata/TagMock.ts
  backend/test/integration/mockdata/UserMock.ts
  backend/test/integration/service/AnswerService.test.ts
  backend/test/integration/service/QuestionService.test.ts
  backend/test/integration/service/UserService.test.ts
  backend/test/testInjectionConfig.ts
  backend/test/unit/.gitkeep
  backend/tsconfig.json
  backend/yarn.lock
  frontend/src/lib/index.ts
Labels: 백엔드, 테스트

#335 Refactor/#330 테스트 코드 추가 작성 및 리팩토링
  backend/test/integration/Answer.test.ts
  backend/test/integration/Question.test.ts
  backend/test/integration/User.test.ts
  backend/test/unit/service/AnswerService.test.ts
  backend/test/unit/service/QuestionService.test.ts
Labels: 백엔드, 테스트

#337 Refactor/#330 깨진 테스트 수정 및 배포 스크립트 수정
  .github/workflows/Deploy.yml
  .github/workflows/Test.yml
  backend/.gitignore
  backend/package.json
  backend/test/integration/Answer.test.ts
  backend/test/integration/Question.test.ts
  backend/test/integration/mockdata/AnswerMock.ts
  backend/test/integration/mockdata/QuestionMock.ts
  backend/test/integration/mockdata/TagMock.ts
  backend/test/integration/mockdata/UserMock.ts
  backend/test/unit/repository/AnswerRepo.test.ts
  backend/test/unit/repository/QuestionRepo.test.ts
  backend/test/unit/repository/UserRepo.test.ts
  backend/test/unit/service/AnswerService.test.ts
  backend/test/unit/service/InjectRepo.ts
  backend/test/unit/service/QuestionService.test.ts
  backend/tsconfig.json
Labels: 백엔드, 인프라 및 배포, 테스트

#341 Refactor/#330 불필요 설정 항목 삭제
  backend/package.json
  backend/test/unit/service/QuestionService.test.ts
  backend/tsconfig.json
Labels: 백엔드, 리팩토링, 테스트

#342 Refactor/#330 빌드 시 테스트 폴더 제외
  backend/tsconfig.json
Labels: 버그, 인프라 및 배포
